# Generated by Django 3.2.11 on 2022-01-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220120_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_id',
            new_name='user',
        ),
    ]
