# Generated by Django 3.2.11 on 2022-01-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220123_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article_news',
            new_name='categoryType',
        ),
    ]
